# Generated by Django 3.0.8 on 2020-08-03 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0004_auto_20200728_1000'),
    ]

    operations = [
        migrations.CreateModel(
            name='basic_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100, null=True)),
                ('lastname', models.CharField(max_length=100, null=True)),
                ('emailaddress', models.CharField(max_length=100, null=True)),
                ('password', models.CharField(max_length=100, null=True)),
                ('confirmpassword', models.CharField(max_length=100, null=True)),
                ('mobilenumber', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='submit',
        ),
    ]
