# Generated by Django 3.0.8 on 2020-08-04 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0006_auto_20200804_1054'),
    ]

    operations = [
        migrations.CreateModel(
            name='lead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Companyname', models.CharField(max_length=100, null=True)),
                ('Companynumber', models.CharField(max_length=100, null=True)),
                ('Companywebsite', models.CharField(max_length=100, null=True)),
                ('Firstname', models.CharField(max_length=100, null=True)),
                ('Lastname', models.CharField(max_length=100, null=True)),
                ('Designation', models.CharField(max_length=100, null=True)),
                ('Phonenumber', models.CharField(max_length=100, null=True)),
                ('CompanyCategory', models.CharField(max_length=100, null=True)),
                ('CompanyType', models.CharField(max_length=100, null=True)),
                ('CompanySize', models.CharField(max_length=100, null=True)),
                ('CompanyRevenue', models.CharField(max_length=100, null=True)),
                ('FacebookLink', models.CharField(max_length=100, null=True)),
                ('TwitterLink', models.CharField(max_length=100, null=True)),
                ('LinkedIN', models.CharField(max_length=100, null=True)),
                ('DetailFrom', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='basic_details',
        ),
    ]
