# Generated by Django 3.0.8 on 2020-08-23 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0009_other_details_emergencycontactname'),
    ]

    operations = [
        migrations.AddField(
            model_name='basic_details',
            name='gender',
            field=models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE'), ('OTHERS', 'OTHERS')], default='MALE', max_length=20),
        ),
    ]
