# Generated by Django 3.0.8 on 2020-08-23 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0011_salary1_dateofjoin'),
    ]

    operations = [
        migrations.AddField(
            model_name='basic_details',
            name='employee_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='other_details',
            name='employee_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='salary1',
            name='employee_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='salary2',
            name='employee_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
