# Generated by Django 3.0.8 on 2020-07-28 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='signup',
            new_name='submit',
        ),
    ]
