# Generated by Django 3.0.8 on 2020-08-04 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0005_auto_20200803_2218'),
    ]

    operations = [
        migrations.AddField(
            model_name='basic_details',
            name='aadharnumber',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='basic_details',
            name='address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='basic_details',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='basic_details',
            name='drivinglicencenumber',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='basic_details',
            name='emergencycontactnumber',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='basic_details',
            name='fathername',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='basic_details',
            name='mothername',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='basic_details',
            name='pincode',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
