# Generated by Django 3.0.8 on 2020-07-28 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0003_auto_20200728_0958'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='signup',
            new_name='submit',
        ),
    ]
