# Generated by Django 3.0.8 on 2020-08-23 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0008_auto_20200823_1906'),
    ]

    operations = [
        migrations.AddField(
            model_name='other_details',
            name='emergencycontactname',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
