# Generated by Django 3.0.8 on 2020-08-23 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0010_basic_details_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='salary1',
            name='dateofjoin',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
